<?php
namespace Ktran\Priapi;

use Illuminate\Support\ServiceProvider;

class PriapiServiceProvider extends ServiceProvider
{
    public function boot(){
        if (file_exists(__DIR__ . '/helpers.php')) {
            require __DIR__ . '/helpers.php';
        }
        $this->loadRoutesFrom(__DIR__.'/routes.php');
        $this->loadViewsFrom(__DIR__.'/Views', 'priapi');
        $this->loadMigrationsFrom(__DIR__.'/Migrations');

        $this->publishes([
            __DIR__.'/assets/' => public_path('vendor/ktran/priapi'),
        ], 'public');
        $this->publishes([
            __DIR__.'/Configs/priapi.php' => config_path('priapi.php'),
        ]);


    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
